language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: A56BiXoY/BiyAKpDPebZCkEldABl+ZxqcGRqrxnHnxGmT1ODOU0HMga9O+5OqfRRFga4VWfZrqRsr4YPuP7nI0gWpZWn682CDepJu8SRo1E6xA3poq9zeCB6UMYQlryimFnt3i98F9fscveydCElx0pSd2C/LpFVcUYi+uVFfJrRXpkPVdVSCrfagVpyQVdJDbqgTbN3rSwXj+onGkOcDNNQDrDB7QDGg1eNKpbFyzGlaK4UnwMbsgh4IOJ7ZEPIZDXn0JUYj7NSp0OdAcVqYt91jp69ywho7lumOgP1eirr/dL9xc9Lj0kUlfXToF5N0PADY84eXApUIt44mi5O41DtdW4WL/GNuLn/h95PNkeF/K0Aa9br8oVreH/jYDbEU9aV85bvoV5X5uGXh5+GfudvWBO+iOkJHULAG8FEpn8JTrVgtwtRVECo8j1BcwWlJsrKZhd4gLXMR2XWCH24Elo4bfsdjOrohasUc1bNj2ljxPyixtPZYdukig5rBwJt7pIPihzYb/PKoF6Wbv3qfJktHS8ABKCUc2RbWKxneHnDV8pVCtp1Es7QDJQsV9xGvBpxROXAHaMZ32CD/GGamThskQGUL4sn4J6BJ8SJOCUGledtfNa43zCHAQ/TC/xkWsK8UYVL/6Zq+dX2+clvcLI0B10SAquMxVUYF23g3xQ=
  file:
    - "hast-util-script-supporting.js"
    - "hast-util-script-supporting.min.js"
  on:
    tags: true
