language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: A/a2DJhbDPXNySgO2T0PVNhn6dVHa/Y5OlzaRm8UveLVqVdYryyeAaC+KCYgrrdBsm6UjcFtXGf+5stbqEk3jSNZgu/nOaauQjpYqqibXn0q9gOsyOPdViLLGTliGddAInySf4r+tLkku4ukXzXSobUj4IDcd7y4IFSOYzxu8PGmfYNeqlB2WAtqPF/y9ER/g9zOzDeFlY8fepLypuovro9L5RBJmcILWc9MD0svxgFaER7aoFgG4Dh6lHZuHufP1qmExK2vIwaddV2ZniCu8yjw7RxojnVM0ToRPLrF8T+z1br4j1Hx444FyyDzOT2feKuhUF4Ig1PLOrQf6r76vKlA8untQoT1WyIPfoYZK1VfI//mVIp7s7ZedF07RcfNdxT66gVHg6kxdYODvZQX4Yn8J8AGzaJOmjVq5n3sXiidE/ISydKVSLxW/PQcn2yx5gVVDAS8+rlsuz0Ya3d3qgYyzNSUNfh0SvdQIkRvBS/O0SyNmz/kN0zmPXA66szJ21D9EyZd576Jn+l3KKfkMP6otqmTwwzoRCzugtzKZ+ijA0jIqvaSLItJGPKz7LGKgXjsZeFdvgMF2mh+nBzilWFiglZqokreweVNd9ZMndcsqhOWFPbnRnoDFAM2AfljYcA6gsAEC1sA4NAf14uDd90ZObvQZdBZ4Z35GEW+fvY=
  file:
    - 'hast-util-script-supporting.js'
    - 'hast-util-script-supporting.min.js'
  on:
    tags: true
